name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-frontend ./frontend

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag my-frontend dydrms0417/my-frontend:latest
          docker push dydrms0417/my-frontend:latest

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.209.43.27 << 'EOF'
            docker pull dydrms0417/my-frontend:latest
            docker stop my-frontend || true
            docker rm my-frontend || true
            docker run -d -p 3000:3000 --name my-frontend dydrms0417/my-frontend:latest
          EOF
