name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-frontend ./frontend

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag my-frontend dydrms0417/my-frontend:latest
          docker push dydrms0417/my-frontend:latest

      - name: Deploy on EC2
        env:
          EC2_HOST: "13.209.43.27"
          EC2_USER: "ubuntu"
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            docker pull dydrms0417/my-frontend:latest
            docker stop my-frontend || true
            docker rm my-frontend || true
            docker run -d -p 3000:3000 --name my-frontend dydrms0417/my-frontend:latest
          EOF
